# Generated by Django 5.0.2 on 2024-03-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookid', models.IntegerField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('publishdate', models.DateField()),
            ],
        ),
    ]
